"""Add tech_stack, project_type, template, status to projects

Revision ID: b93e6ab5052f
Revises: 328cb9de3afa
Create Date: 2025-09-30 00:57:35.179203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b93e6ab5052f'
down_revision = '328cb9de3afa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_file_path', 'files', ['project_id', 'path'])
    op.drop_constraint(op.f('files_project_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('tech_stack', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('project_type', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('template', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'last_opened_at')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'template')
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'tech_stack')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_project_id_fkey'), 'files', 'projects', ['project_id'], ['id'])
    op.drop_constraint('uq_project_file_path', 'files', type_='unique')
    # ### end Alembic commands ###